version: '3'

services:
  backend:
    build: ./
    container_name: SkyLink-Project_container
    working_dir: /SkyLink-Project
    ports:
      - "8010:8000"
    command:
      - ./commands/start_django_server.sh
    volumes:
      - ./src:/SkyLink-Project/src
      - ./commands:/SkyLink-Project/commands
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15.7
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data: { }