version: '3'

services:
  backend:
    build: ./
    container_name: SkyLink-Project_container
    working_dir: /SkyLink-Project
    ports:
      - "8010:8000"
    command:
      - ./commands/start_django_server.sh
    volumes:
      - ./src:/SkyLink-Project/src
      - ./commands:/SkyLink-Project/commands

