# Generated by Django 4.2 on 2025-03-09 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("airport", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="flightseat",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_seats",
                to="airport.flight",
            ),
        ),
        migrations.AddField(
            model_name="flightseat",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_seats",
                to="airport.seat",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_airplane",
                to="airport.airplane",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(related_name="flight_crew", to="airport.crew"),
        ),
        migrations.AddField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_route",
                to="airport.route",
            ),
        ),
        migrations.AddField(
            model_name="airplane",
            name="airplane_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="airplane",
                to="airport.airplanetype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("flight_seat", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together={("airplane", "seat", "row")},
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "destination")},
        ),
        migrations.AlterUniqueTogether(
            name="flightseat",
            unique_together={("seat", "flight")},
        ),
    ]
