# Generated by Django 5.1.7 on 2025-03-26 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("airport", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_destination",
                to="airport.airport",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_source",
                to="airport.airport",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_route",
                to="airport.route",
            ),
        ),
        migrations.AddField(
            model_name="seat",
            name="airplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats_airplane",
                to="airport.airplane",
            ),
        ),
        migrations.AddField(
            model_name="flightseat",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_seats",
                to="airport.seat",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="flight_seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_flight",
                to="airport.flightseat",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_order",
                to="airport.order",
            ),
        ),
        migrations.AddField(
            model_name="tariff",
            name="ticket_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tariff",
                to="airport.ticketclass",
            ),
        ),
        migrations.AddField(
            model_name="seat",
            name="ticket_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seat",
                to="airport.ticketclass",
            ),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("source", "destination", "code_route"),
                name="unique_route_source",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="flightseat",
            unique_together={("seat", "flight")},
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("flight_seat",), name="unique_flight_seat_order"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together={("airplane", "seat", "row")},
        ),
    ]
