# Generated by Django 4.2 on 2025-03-10 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="geographical_coordinates",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
