# Generated by Django 4.2 on 2025-03-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_airport_geographical_coordinates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.IntegerField(),
        ),
    ]
