# Generated by Django 4.2 on 2025-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_alter_airplanetype_name_alter_route_distance"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="route",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("source", "destination", "code_route"),
                name="unique_route_source",
            ),
        ),
    ]
